Implemented Diamond Printing
arivazhagan-tmm/Assignments pull request #17
Opened 2023-09-01 09:33 UTC by arivazhagan-tmm

2023-09-04 04:07 UTC, ravin-imm requested changes

2023-09-04 04:07 UTC, ravin-imm commented on T09/Program.cs
> +         Write ("\nEnter the no of rows\t : ");
The space between the message and the colon is more. It can be trimmed.
<img width="242" alt="image" src="https://github.com/arivazhagan-tmm/Assignments/assets/75829870/942e6a29-2472-40e3-8019-2b6cf57bea04">

2023-09-04 04:07 UTC, ravin-imm commented on T09/T09.csproj
> +</Project>
Don't create another project for each assignment. Create a new branch from the main and work on it. Just push only the changes.

2023-09-04 05:04 UTC, arivazhagan-tmm commented on T09/T09.csproj
> +</Project>
Currently my main branch contains the "Expression Evaluator" code and hence I have created separate solution to each assignments as the same way I submitted previous assignments.

2023-10-26 09:57 UTC, ravin-imm approved these changes

2023-10-26 09:57 UTC, closed without merging