T22 - Swap Indices
arivazhagan-tmm/Assignments pull request #27
Opened 2023-10-25 09:34 UTC by arivazhagan-tmm

2023-10-25 10:55 UTC, varalakshmi-imm requested changes

2023-10-25 10:55 UTC, varalakshmi-imm commented on T22/Program.cs
> +   private static void Main (string[] args) {
Can remove unused args

2023-10-25 10:55 UTC, varalakshmi-imm commented on T22/Program.cs
> +         Write ("Do you want to continue? (Y/N) : ");
```suggestion
         Write ("Do you want to continue? (Y/N): ");

```

2023-10-25 10:55 UTC, varalakshmi-imm commented on T22/Program.cs
> +         var (m, n) = (num[j], num[i]);
Have a separate Swap method which takes the number and returns the swapped number.
If it is a char array you can do tuple swap.

2023-10-25 10:55 UTC, varalakshmi-imm commented on T22/Program.cs
> +         var message = i >= max ? $"\tIndex should be less than {max}" : "\tPlease enter valid numeric value!";
-1 is not handled for index

2023-10-25 12:02 UTC, arivazhagan-tmm commented on T22/Program.cs
> +         var (m, n) = (num[j], num[i]);
I have simplified the code without using swap logic.

2023-10-26 04:03 UTC, varalakshmi-imm commented on T22/Program.cs
> +         var (m, n) = (num[j], num[i]);
I think this assignment expects to have a method to swap.

2023-10-26 04:04 UTC, varalakshmi-imm requested changes
Implement a Swap method

2023-10-26 07:33 UTC, varalakshmi-imm requested changes
I guess I didn't make it clear.
Swap method should take the number and the indices and return the new number.

2023-10-26 10:11 UTC, varalakshmi-imm approved these changes

2023-10-26 10:11 UTC, varalakshmi-imm commented on T22/Program.cs
> +      (chars[index1], chars[index2]) = (chars[index2], chars[index1]);
![image](https://github.com/arivazhagan-tmm/Assignments/assets/75829713/e2bd301f-c77e-4fc8-af4b-7f59f9ba861b)

@arivazhagan-tmm Always use expression body or single line methods

2023-10-26 10:11 UTC, closed without merging